spring:
#  profiles:
#    active: test
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update