spring:
  #  profiles:
  #    active: dev
  config:
    import: file:env.properties
  datasource:
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database: ${DB_DATABASE}
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        generate_statistics: false
